package Frames;

import javax.swing.*;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.text.BadLocationException;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.InputMethodEvent;
import java.awt.event.InputMethodListener;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;

import producerconsumer.Consumer;
import producerconsumer.Monitor;

public class TiendaA {
    private JButton button1;
    private JPanel panel1;
    public JTextArea textArea1;
    private JSpinner spinner1;
    private JButton enviarButton;
    public String cantidadProducto;

    public TiendaA() {
        textArea1.setSize(150, 150);
        spinner1.setSize(100, 100);
        spinner1.setVisible(false);
        button1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                //JOptionPane.showMessageDialog(null, "Hello World");
                textArea1.append("hola que hace \n");
                spinner1.setVisible(true);
                textArea1.append("¿Cuanto quieres consumir? \n");
            }
        });

        spinner1.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                cantidadProducto = spinner1.getValue().toString();
            }
        });

        enviarButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Consumer.Consumer(textArea1, cantidadProducto);
                spinner1.setVisible(false);
            }
        });
    }


    public static void main(String args[]) throws IOException, InterruptedException {
        JFrame frame = new JFrame("TiendaA");
        TiendaA tienda = new TiendaA();
        frame.setContentPane(tienda.panel1);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
        frame.setResizable(false);

        frame.setSize(500, 500);
        //frame.setLocation(200, 200);
        //frame.setBounds(400,400, 400, 400);
        frame.setLocationRelativeTo(null);


        //Monitor.main(args);
        //Consumer.main(args);

    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        panel1.setAlignmentX(1.0f);
        panel1.setAlignmentY(1.0f);
        panel1.setPreferredSize(new Dimension(500, 500));
        enviarButton = new JButton();
        enviarButton.setHorizontalAlignment(0);
        enviarButton.setMargin(new Insets(0, 0, 0, 0));
        enviarButton.setText("ENVIAR");
        enviarButton.setVerticalAlignment(0);
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipadx = 10;
        gbc.ipady = 10;
        panel1.add(enviarButton, gbc);
        spinner1 = new JSpinner();
        spinner1.setBackground(new Color(-12828863));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.gridheight = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipadx = 5;
        gbc.ipady = 5;
        panel1.add(spinner1, gbc);
        button1 = new JButton();
        button1.setText("CONSUMIR");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipadx = 10;
        gbc.ipady = 10;
        panel1.add(button1, gbc);
        textArea1 = new JTextArea();
        textArea1.setEditable(false);
        textArea1.setLineWrap(true);
        textArea1.setPreferredSize(new Dimension(100, 100));
        textArea1.setWrapStyleWord(true);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridheight = 4;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.ipadx = 50;
        gbc.ipady = 25;
        panel1.add(textArea1, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
